run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/2gc-dev/cloudbridge-client
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gci
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - shadow
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - funlen
        - gocyclo
        - dupl
    - path: pkg/relay/tunnel_test\.go
      linters:
        - goconst
    - path: pkg/auth/auth_test\.go
      linters:
        - goconst
    - path: test/integration_test\.go
      linters:
        - goconst
        - funlen
        - gocyclo
    - path: pkg/service/service\.go
      linters:
        - gosec
    - path: pkg/config/config\.go
      linters:
        - gosec
    - path: pkg/metrics/metrics\.go
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0 