run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 50
  dupl:
    threshold: 300
  goconst:
    min-len: 8
    min-occurrences: 15
  misspell:
    locale: US
  lll:
    line-length: 200
  funlen:
    lines: 300
    statements: 150

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - funlen
        - gocyclo
        - dupl
        - gosec
    - path: pkg/relay/tunnel_test\.go
      linters:
        - goconst
        - gosec
    - path: pkg/auth/auth_test\.go
      linters:
        - goconst
        - gosec
    - path: test/integration_test\.go
      linters:
        - goconst
        - funlen
        - gocyclo
        - gosec
    - path: pkg/service/service\.go
      linters:
        - gosec
    - path: pkg/config/config\.go
      linters:
        - gosec
    - path: pkg/metrics/metrics\.go
      linters:
        - gosec
    - path: pkg/relay/client\.go
      linters:
        - gosec
    - path: cmd/cloudbridge-client/main\.go
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0 