run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/2gc-dev/cloudbridge-client

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gci
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - gocyclo
        - dupl
    - path: pkg/relay/tunnel_test\.go
      linters:
        - gomnd # Allow magic numbers in tests
    - path: pkg/auth/auth_test\.go
      linters:
        - gomnd # Allow magic numbers in tests
    - path: test/integration_test\.go
      linters:
        - gomnd # Allow magic numbers in tests
        - funlen # Allow longer test functions
        - gocyclo # Allow complex test logic

  max-issues-per-linter: 0
  max-same-issues: 0 