relay:
  host: "edge.2gc.ru"
  port: 8080
  timeout: "30s"
  tls:
    enabled: true
    min_version: "1.3"
    verify_cert: true
    ca_cert: ""
    client_cert: ""
    client_key: ""
    server_name: ""

auth:
  type: "jwt"
  secret: "your-jwt-secret-here"
  keycloak:
    enabled: false
    server_url: "https://keycloak.example.com"
    realm: "cloudbridge"
    client_id: "relay-client"

rate_limiting:
  enabled: true
  max_retries: 3
  backoff_multiplier: 2.0
  max_backoff: "30s"

logging:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  prometheus_port: 9090
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true

performance:
  enabled: true
  optimization_mode: "high_throughput"
  gc_percent: 100
  memory_ballast: true 