# CloudBridge Client Configuration

# TLS Configuration
tls:
  enabled: true
  cert_file: "/etc/cloudbridge/certs/client.crt"
  key_file: "/etc/cloudbridge/certs/client.key"
  ca_file: "/etc/cloudbridge/certs/ca.crt"

# Server Configuration
server:
  host: edge.2gc.ru
  port: 8080
  jwt_token: "your-jwt-token"

# Tunnel Configuration
tunnel:
  local_port: 3389
  reconnect_delay: 5  # seconds
  max_retries: 3

# Metrics Configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  interval: 15s

# Health Configuration
health:
  enabled: true
  path: "/health"
  check_interval: 30s

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error
  file: "/var/log/cloudbridge-client/client.log"
  max_size: 10    # MB
  max_backups: 3
  max_age: 28     # days
  compress: true
  format: "json" 