name: Build MSI Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  CGO_ENABLED: 0

jobs:
  build-msi:
    name: Build MSI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install WiX Toolset
        run: |
          # Download WiX Toolset
          $url = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
          $output = "wix311.exe"
          Write-Host "Downloading WiX Toolset..."
          Invoke-WebRequest -Uri $url -OutFile $output
          
          # Install WiX Toolset
          Write-Host "Installing WiX Toolset..."
          Start-Process -FilePath $output -ArgumentList "/quiet" -Wait
          
          # Add WiX to PATH
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
          
          # Verify installation
          Write-Host "Verifying WiX installation..."
          if (Test-Path "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe") {
              Write-Host "WiX Toolset installed successfully"
          } else {
              Write-Host "WiX Toolset installation failed"
              exit 1
          }

      - name: Build Windows executable
        run: |
          go build -v -ldflags="-s -w" -o cloudbridge-client.exe ./cmd/cloudbridge-client

      - name: Create MSI package
        run: |
          # Create directory and copy files
          New-Item -ItemType Directory -Force -Path msi
          Copy-Item -Path cloudbridge-client.exe -Destination msi\
          Copy-Item -Path config\config.yaml -Destination msi\
          
          # Build MSI
          Write-Host "Building MSI package..."
          $env:WIX = "C:\Program Files (x86)\WiX Toolset v3.11"
          & "$env:WIX\bin\candle.exe" -out "cloudbridge-client.wixobj" "deploy\windows\cloudbridge-client.wxs"
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          & "$env:WIX\bin\light.exe" -ext WixUIExtension -out "cloudbridge-client.msi" "cloudbridge-client.wixobj"
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          
          # Verify MSI was created
          if (Test-Path "cloudbridge-client.msi") {
              Write-Host "MSI package created successfully"
          } else {
              Write-Host "Failed to create MSI package"
              exit 1
          }

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudbridge-client.msi
          path: cloudbridge-client.msi
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: cloudbridge-client.msi
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 