name: Build MSI Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Install WiX Toolset
        run: |
          Write-Host "Downloading WiX Toolset..."
          $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
          $wixInstaller = "$env:RUNNER_TEMP\wix311.exe"
          Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
          
          Write-Host "Installing WiX Toolset..."
          Start-Process -FilePath $wixInstaller -ArgumentList "/quiet" -Wait
          
          Write-Host "Updating PATH..."
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
          
          Write-Host "Verifying WiX installation..."
          if (Test-Path "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe") {
              Write-Host "WiX Toolset installed successfully"
          } else {
              Write-Error "WiX Toolset installation failed"
              exit 1
          }

      - name: Build Windows Binary
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "1"
          go build -o cloudbridge-client.exe ./cmd/cloudbridge-client

      - name: Create MSI Package
        run: |
          Write-Host "Creating MSI package..."
          
          # Create directories
          New-Item -ItemType Directory -Force -Path "msi\bin"
          New-Item -ItemType Directory -Force -Path "msi\config"
          New-Item -ItemType Directory -Force -Path "msi\logs"
          
          # Copy files
          Copy-Item "cloudbridge-client.exe" -Destination "msi\bin\"
          Copy-Item "config.yaml" -Destination "msi\config\"
          
          # Compile WiX source
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -out "msi\CloudBridgeClient.wixobj" "msi\CloudBridgeClient.wxs"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to compile WiX source"
              exit 1
          }
          
          # Create MSI package
          & "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -out "CloudBridgeClient.msi" "msi\CloudBridgeClient.wixobj"
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create MSI package"
              exit 1
          }
          
          # Verify MSI was created
          if (Test-Path "CloudBridgeClient.msi") {
              Write-Host "MSI package created successfully"
          } else {
              Write-Error "MSI package creation failed"
              exit 1
          }

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudbridge-client-msi
          path: CloudBridgeClient.msi
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: CloudBridgeClient.msi
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 