name: Build MSI Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install WiX
        run: |
          Write-Host "Installing WiX v4..."
          dotnet tool install --global wix
          Write-Host "WiX installation completed"

      - name: Build Windows Binary
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "1"
          go build -o cloudbridge-client.exe ./cmd/cloudbridge-client

      - name: Create MSI Package
        run: |
          Write-Host "Creating MSI package..."
          
          # Create directories
          New-Item -ItemType Directory -Force -Path "msi\bin"
          New-Item -ItemType Directory -Force -Path "msi\config"
          New-Item -ItemType Directory -Force -Path "msi\logs"
          
          # Copy files
          Copy-Item "cloudbridge-client.exe" -Destination "msi\bin\"
          Copy-Item "config.yaml" -Destination "msi\config\"
          
          Write-Host "Building MSI package with WiX v4..."
          wix build msi\CloudBridgeClient.wxs -out CloudBridgeClient.msi
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to create MSI package"
              exit 1
          }
          
          # Verify MSI was created
          if (Test-Path "CloudBridgeClient.msi") {
              Write-Host "MSI package created successfully"
              Get-Item "CloudBridgeClient.msi" | Select-Object Name, Length, LastWriteTime
          } else {
              Write-Error "MSI package creation failed"
              exit 1
          }

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudbridge-client-msi
          path: CloudBridgeClient.msi
          if-no-files-found: error

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: CloudBridgeClient.msi
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 